"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_pink_bold)\
$os\

[](bg:color_peach fg:color_pink_bold)\
$directory\

[](fg:color_peach bg:color_purple)\
$git_branch\
$git_status\

[](fg:color_purple bg:color_teal)\
$rust\
$python\

[](fg:color_teal bg:color_deep_wine)\
$docker_context\
$conda\
$pixi\

[](fg:color_deep_wine bg:color_dark_purple)\
$time\

[ ](fg:color_dark_purple)\
$line_break$character"""

add_newline = true

palette = 'magical_palette'

[palettes.magical_palette]
# Seleção das cores enviadas para melhor harmonia:
color_light_pink = '#fde6ee' # Texto muito claro
color_peach      = '#f6cdcb' # Fundo diretório
color_pink_bold  = '#ff3e8b' # Rosa vibrante (OS/User)
color_purple     = '#ae72d4' # Roxo médio (Git)
color_teal       = '#527e81' # Cerceta/Azul escuro (Linguagens)
color_deep_wine  = '#76445f' # Vinho (Docker)
color_dark_purple = '#47324E' # (Baseado na anterior para fechamento escuro)
color_yellow     = '#fbbf2d' # Amarelo (Avisos)

[os]
disabled = false
style = "bg:color_pink_bold fg:color_light_pink"

[os.symbols]
Linux = "󰌽"
Arch = "󰼁 "

[username]
show_always = true
style_user = "bg:color_pink_bold fg:color_light_pink"
style_root = "bg:color_pink_bold fg:color_light_pink"
format = '[ $user ]($style)'

[directory]
style = "fg:color_pink_bold bg:color_peach"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol $branch ](fg:color_light_pink bg:color_purple)]($style)'

[git_status]
style = "bg:color_purple"
format = '[[($all_status$ahead_behind )](fg:color_light_pink bg:color_purple)]($style)'

[rust]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_peach bg:color_teal)]($style)'

[python]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_peach bg:color_teal)]($style)'

[docker_context]
symbol = ""
style = "bg:color_deep_wine"
format = '[[ $symbol( $context) ](fg:color_light_pink bg:color_deep_wine)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_dark_purple"
format = '[[ $time ](fg:color_light_pink bg:color_dark_purple)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:color_pink_bold)'
error_symbol = '[](bold fg:color_yellow)'
vimcmd_symbol = '[](bold fg:color]'
